### ISSUE TITLE
Are  we allowed to change the M117 format?

### ISSUE THREAD

**Issue by CptanPanic** [arhi/OctoPrint-gcodestatEstimator#1]
I don't ever print anything that takes weeks, so would like to make the format fit my LCD screen on my Ender3. I see you mention format in the Readme.md but it isn't clear to me if you are saying we can change it to those 4 different formats or what? If you are saying that, it might be helpful to include what the format specifiers are for gcodestat to make sure it matches what you are expecting.
Thanks.

**Comment by arhi** [comment]
"are we allowed" - well the code is open so feel free to change anything :D 

now wrt what the code "expect" to achieve as the M117 value is one of these regexes
```
    pw = re.compile('M117 ([0-9]+)%+ Remaining ([0-9]+) weeks ([0-9]+) days \( ([0-9]+):([0-9]+):([0-9]+) \)')
    pd = re.compile('M117 ([0-9]+)%+ Remaining ([0-9]+) days \( ([0-9]+):([0-9]+):([0-9]+) \)')
    ph = re.compile('M117 ([0-9]+)%+ Remaining \( ([0-9]+):([0-9]+):([0-9]+) \)')
    pm = re.compile('M117 ([0-9]+)%+ Remaining \( ([0-9]+):([0-9]+) \)')
    ps = re.compile('M117 ([0-9]+)%+ Remaining \( ([0-9]+) \)')
```

so if you look at the "largest" one 

M117 100% Remaining 1 weeks 6 days ( 07:54:19 )

you can miss weeks, or weeks and days, or weeks and days and hours... 
so you can't have weeks and then miss days or have days and miss hours.. 

so as readme states any of the following would be properly recognized

    M117 100% Remaining 1 weeks 6 days ( 07:54:19 )
    M117 100% Remaining 4 days ( 02:04:19 )
    M117 35% Remaining ( 12:43:04 )
    M117 17% Remaining ( 43:04 )
    M117 5% Remaining ( 04 )

if you need to use a different format, for e.g. lose the "Remaining" string as it can't fit on the LCD then you need to edit the code .. or if there's a specific format you would like lemme know and I can add it to the code myself. There's probbly a better way to handle this ( https://github.com/arhi/OctoPrint-gcodestatEstimator/blob/57221211ed151cc784b208d2c23a362119709cc1/octoprint_gcodestatEstimator/__init__.py#L25 and next few lines) but I'm not really a python developer so I did it in a "works for me" fashion hoping a real python expert would check it out and offer a better solution :D

**Comment by arhi** [comment]
that's what gcodestatEstimator supports, as for the gcodestat itself, the way you can format output is described here: https://github.com/arhi/gcodestat#m117_format
the issue with it is that if you for e.g. remove the "Remaning" word the gcodestatEstimator will not recognize the value

**Comment by CptanPanic** [comment]
Thanks I went with 3rd option:
--m117_format "M117 %p%% Remaining ( %h:%m:%s )"
